esphome:
  name: ultrasonic_wind_sensor
  friendly_name: ultrasonic_wind_sensor

esp32:
  board: esp32s




# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "your_encryption_key"

ota:
  password: "your_ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ap_timeout: 180s
    ssid: "Toshiba-Ac"
    password: "your_ap_password"

captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

external_components:
  - source:
      type: git
      url: https://github.com/makusets/esphome_ultrasonic_wind
    refresh: 0s  # Optional: force update every time

sensor:
  # Optional: publish BME280 values separately
  - platform: bme280_i2c
    temperature:
      name: "Ambient Temperature"
      id: bme_temp
    pressure:
      name: "Atmospheric Pressure"
    humidity:
      name: "Relative Humidity"
      id: bme_hum
    id: internal_bme
    update_interval: 5s

  # Ultrasonic wind sensor via TUSS4470
  - platform: ultrasonic_wind
    cs_pin: GPIO5 
    burst_pin: GPIO33
    tof_interrupt_pin: GPIO14
    temperature_sensor: bme_temp
    humidity_sensor: bme_hum
    sensor_distance: 200.0  # in mm
    update_interval: 5s
    wind_speed:
      name: "Ultrasonic Wind Speed"
      unit_of_measurement: "km/h"
      icon: "mdi:weather-windy"
    wind_direction:
      name: "Ultrasonic Wind Direction"
      unit_of_measurement: "°"
      icon: "mdi:compass"

    