esphome:
  name: ultrasonic_wind_sensor
  friendly_name: ultrasonic_wind_sensor

esp32:
  board: esp32s




# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "your_encryption_key"

ota:
  password: "your_ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ap_timeout: 180s
    ssid: "Toshiba-Ac"
    password: "your_ap_password"

captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

external_components:
  - source:
      type: git
      url: https://github.com/makusets/esphome_ultrasonic_wind
    components: [ultrasonic_wind]
    refresh: 0s  # Optional: force update every time

sensor:
  - platform: ultrasonic_wind
    burst_pin: GPIO33  # Connects to TUSS4470 IO2, optional, default GPIO33
    wind_speed:
      name: "Ultrasonic Wind Speed"
    wind_direction:
      name: "Ultrasonic Wind Direction"
    update_interval: 5s




    