name: "Ultrasonic Wind Sensor"
files:
  - __init__.py
  - sensor.py
  - ultrasonic_wind.cpp
  - ultrasonic_wind.h
  - component.yaml
platforms: ["esp32"]
dependencies: ["sensor", "spi", "gpio"]
sensor:
  - platform: ultrasonic_wind